import { describe, it, expect } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, utimesSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { titleFrom, listSessionsFor, deleteClaudeSession } from "../src/projects.js";

const line = (o: unknown) => JSON.stringify(o);

describe("titleFrom", () => {
  it("prefers an ai-title entry (Claude Code's aiTitle field)", () => {
    const jsonl = [
      line({ type: "ai-title", aiTitle: "Fix the parser" }),
      line({ type: "user", message: { role: "user", content: "do the thing" } }),
    ].join("\n");
    expect(titleFrom(jsonl)).toBe("Fix the parser");
  });
  it("accepts a legacy ai-title `value` field too", () => {
    expect(titleFrom(line({ type: "ai-title", value: "Legacy title" }))).toBe("Legacy title");
  });
  it("falls back to the first user prompt (truncated)", () => {
    const long = "x".repeat(100);
    const jsonl = line({ type: "user", message: { role: "user", content: long } });
    expect(titleFrom(jsonl)).toBe(long.slice(0, 60) + "…");
  });
  it("returns 'Untitled' when there is nothing", () => {
    expect(titleFrom(line({ type: "mode", value: "x" }))).toBe("Untitled");
  });
  it("titles a slash-command session by the command name", () => {
    const content = "<command-name>superpowers:brainstorming</command-name>\n<command-message>superpowers:brainstorming is running…</command-message>\n<command-args></command-args>";
    const jsonl = line({ type: "user", message: { role: "user", content } });
    expect(titleFrom(jsonl)).toBe("/superpowers:brainstorming");
  });
  it("normalizes a command name that already has a leading slash", () => {
    const content = "<command-name>/clear</command-name>";
    expect(titleFrom(line({ type: "user", message: { role: "user", content } }))).toBe("/clear");
  });
  it("strips the local-command-caveat wrapper and keeps the real prose", () => {
    const content = "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>\nActually fix the bug in the parser";
    expect(titleFrom(line({ type: "user", message: { role: "user", content } }))).toBe("Actually fix the bug in the parser");
  });
  it("skips a pure-injection first message and uses the next real prompt", () => {
    const jsonl = [
      line({ type: "user", message: { role: "user", content: "<local-command-caveat>Caveat: …</local-command-caveat>" } }),
      line({ type: "user", message: { role: "user", content: "the real first prompt" } }),
    ].join("\n");
    expect(titleFrom(jsonl)).toBe("the real first prompt");
  });
  it("still prefers an ai-title over a slash command", () => {
    const jsonl = [
      line({ type: "user", message: { role: "user", content: "<command-name>foo</command-name>" } }),
      line({ type: "ai-title", aiTitle: "Real summary" }),
    ].join("\n");
    expect(titleFrom(jsonl)).toBe("Real summary");
  });
});

describe("listSessionsFor", () => {
  it("returns one SessionMeta per session file, newest first, titled + previewed", () => {
    const home = mkdtempSync(join(tmpdir(), "claude-ls-"));
    const dir = join(home, "projects", "-Users-me-app");
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "s1.jsonl"), [
      line({ cwd: "/Users/me/app", type: "ai-title", aiTitle: "First" }),
      line({ type: "user", message: { role: "user", content: "hi" } }),
      line({ type: "assistant", message: { role: "assistant", content: [{ type: "text", text: "yo" }] } }),
    ].join("\n") + "\n");
    writeFileSync(join(dir, "s2.jsonl"), [
      line({ cwd: "/Users/me/app", type: "user", message: { role: "user", content: "second session prompt" } }),
    ].join("\n") + "\n");
    // Pin distinct mtimes so "newest first" is deterministic — on fast CI
    // filesystems both writes can land in the same coarse mtime tick otherwise.
    utimesSync(join(dir, "s1.jsonl"), new Date(1_000), new Date(1_000));
    utimesSync(join(dir, "s2.jsonl"), new Date(2_000), new Date(2_000));
    const sessions = listSessionsFor(home, "/Users/me/app");
    expect(sessions.map((s) => s.sessionId)).toEqual(["s2", "s1"]);
    const s1 = sessions.find((s) => s.sessionId === "s1")!;
    expect(s1.title).toBe("First");
    expect(s1.preview?.text).toBe("yo");
    const s2 = sessions.find((s) => s.sessionId === "s2")!;
    expect(s2.title).toBe("second session prompt");
    rmSync(home, { recursive: true, force: true });
  });
  it("returns [] for an unknown project", () => {
    const home = mkdtempSync(join(tmpdir(), "claude-ls2-"));
    mkdirSync(join(home, "projects"), { recursive: true });
    expect(listSessionsFor(home, "/nope")).toEqual([]);
    rmSync(home, { recursive: true, force: true });
  });
});

describe("deleteClaudeSession", () => {
  it("removes the session file by id and drops it from listings", () => {
    const home = mkdtempSync(join(tmpdir(), "claude-del-"));
    const dir = join(home, "projects", "-Users-me-app");
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "keep.jsonl"), line({ cwd: "/Users/me/app", type: "user", message: { role: "user", content: "a" } }) + "\n");
    writeFileSync(join(dir, "gone.jsonl"), line({ cwd: "/Users/me/app", type: "user", message: { role: "user", content: "b" } }) + "\n");
    expect(deleteClaudeSession(home, "gone")).toBe(true);
    expect(listSessionsFor(home, "/Users/me/app").map((s) => s.sessionId)).toEqual(["keep"]);
    expect(deleteClaudeSession(home, "missing")).toBe(false);   // unknown id
    rmSync(home, { recursive: true, force: true });
  });
});
